"""initial setup

Revision ID: 0882530520ba
Revises: 
Create Date: 2023-05-31 16:57:26.280968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0882530520ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('parent_id', sa.BIGINT(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('meta_title', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('type', sa.SMALLINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('role_id', sa.SMALLINT(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(), nullable=True),
    sa.Column('mobile', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('intro', sa.TEXT(), nullable=True),
    sa.Column('profile', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('order',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.SMALLINT(), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.Column('sub_total', sa.FLOAT(), nullable=False),
    sa.Column('item_discount', sa.FLOAT(), nullable=False),
    sa.Column('tax', sa.FLOAT(), nullable=False),
    sa.Column('shipping', sa.FLOAT(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('promo', sa.VARCHAR(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=False),
    sa.Column('grand_total', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('product_category',
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_index(op.f('ix_product_category_category_id'), 'product_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_category_product_id'), 'product_category', ['product_id'], unique=False)
    op.create_table('product_meta',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_meta_product_id'), 'product_meta', ['product_id'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('mobile', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('line_1', sa.VARCHAR(), nullable=True),
    sa.Column('line_2', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('province', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_order_id'), 'address', ['order_id'], unique=False)
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('brand_id', sa.BIGINT(), nullable=False),
    sa.Column('supplier_id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('sku', sa.VARCHAR(), nullable=False),
    sa.Column('mrp', sa.FLOAT(), nullable=False),
    sa.Column('discount', sa.FLOAT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.SMALLINT(), nullable=False),
    sa.Column('sold', sa.SMALLINT(), nullable=False),
    sa.Column('available', sa.SMALLINT(), nullable=False),
    sa.Column('defective', sa.SMALLINT(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_brand_id'), 'item', ['brand_id'], unique=False)
    op.create_index(op.f('ix_item_order_id'), 'item', ['order_id'], unique=False)
    op.create_index(op.f('ix_item_product_id'), 'item', ['product_id'], unique=False)
    op.create_index(op.f('ix_item_supplier_id'), 'item', ['supplier_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.SMALLINT(), nullable=False),
    sa.Column('mode', sa.SMALLINT(), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_order_id'), 'transaction', ['order_id'], unique=False)
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('item_id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('sku', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('discount', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.SMALLINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_item_id'), 'order_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_product_id'), 'order_item', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_product_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_order_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_item_supplier_id'), table_name='item')
    op.drop_index(op.f('ix_item_product_id'), table_name='item')
    op.drop_index(op.f('ix_item_order_id'), table_name='item')
    op.drop_index(op.f('ix_item_brand_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_index(op.f('ix_address_order_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_product_meta_product_id'), table_name='product_meta')
    op.drop_table('product_meta')
    op.drop_index(op.f('ix_product_category_product_id'), table_name='product_category')
    op.drop_index(op.f('ix_product_category_category_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
